#!/bin/bash

# Directory containing Solidity contracts
SOURCE_DIR="dataset/aisc/source/unchecked_low_level_calls"

# Directory to store the resulting bytecode
BYTECODE_DIR="dataset/aisc/bytecode/unchecked_low_level_calls"

# Check if solc is installed
if ! command -v solc &> /dev/null
then
    echo "solc could not be found, please install it."
    exit 1
fi

# Create the bytecode directory if it does not exist
mkdir -p "$BYTECODE_DIR"

# Loop over all solidity files in the source directory
for sol_file in "$SOURCE_DIR"/*.sol; do
    # Extract the filename without the extension
    filename=$(basename -- "$sol_file")
    contract_name="${filename%.*}"

    # Compile the contract to bytecode
    echo "Compiling $sol_file..."
    solc --bin "$sol_file" --overwrite -o "$BYTECODE_DIR" --optimize

    # Rename the generated bytecode file to match the contract name
    if [ -f "$BYTECODE_DIR/$contract_name.bin" ]; then
        mv "$BYTECODE_DIR/$contract_name.bin" "$BYTECODE_DIR/$contract_name.bytecode"
    fi
done

echo "Compilation complete. Bytecode stored in $BYTECODE_DIR"
